/**
 * @description This is the AccountConstants class which contains all the constants related to the Account.
 * @author Suresh Kumar
 * @jira BIZ-68167
 */
public with sharing class AccountConstants {
     // Types
     public static final String TYPE_PROSPECT = 'Prospect';
     public static final String TYPE_CLIENT = 'Client';
     public static final String TYPE_CLIENT_LAPSED = 'Client - Lapsed';
}