/**
* @description Constant class for address object
* @author Pooja Hemrajani
* @jira BIZ-68205
**/
public with sharing class AddressConstants {
	
    // Address Status
    public static final String PENDING_GOVERNANCE = 'Pending Governance';
    public static final String VERIFICATION_APPROVED = 'Verification Approved';
    
    // Country Values
    public static final String UNITES_STATES = 'United States';
}