/**
* @description Constant class for Product object
* @author Sahal Mohamed
* @jira BIZ-78712
**/
public with sharing class ProductConstants {
    
    // Product Types
    public static final String PRODUCT_TYPE_SOFTWARE = 'Software';
    public static final String PRODUCT_TYPE_MAINTENANCE = 'Maintenance';
    public static final String PRODUCT_TYPE_SUPPORT = 'Support';
    
    // Guided Selling Types
    public static final String GUIDED_SELLING_TYPE_SOFTWARE = 'Software';
}